name: React Pokedex CI/CD

on: 
  schedule:
    - cron '0 */24 * * *'

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:
    
permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy
        uses: peaceiris/upload-pages-artifact@v1
        with:
          publish_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}